name: PR Validation Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Check-Only Validation in Salesforce
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
       
      - name: Set up Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Write JWT key to file
        #if: false
        run: |
            printf '%s' "${{ secrets.SF_JWT_KEY }}" > server.key
            #echo "${{ secrets.SF_JWT_KEY }}" | > server.key

      - name: Check key file
        run: |
          ls -l server.key
          head -n 5 server.key

      - name: Authenticate to Salesforce
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --alias pr-validate-org \
            --set-default

      - name: Run check-only deploy
        run: |
          sf project deploy validate \
            --target-org pr-validate-org \
            --ignore-warnings \
            --test-level RunLocalTests

      - name: Clean up auth file
        run: rm server.key
